### ISSUE TITLE
Deleting repo causes endless error loop in 'scale-up' Lambda?

### ISSUE THREAD

**Issue by boldandbusted** [philips-labs/terraform-aws-github-runner#1079]
Howdy. Thank you for this awesome module. :) Today, a user created a repo from a GitHub Repo Template which contains Workflows, then quickly deleted it. It appears that this has created an endless loop in the 'scale-up' runner trigged by a message on the SQS queue. Log entries for the 'scale-up' Lambda like those below repeat every 3 minutes since the repo was deleted.

First, the SQS message:

```
START RequestId: 28287858-b79a-57a8-92a9-21d54736de72 Version: $LATEST
--
{
Records: [
{
messageId: 'a29239f1-839a-42b4-a952-70dd97c2f565',
receiptHandle: 'AQEBFbjGTl7S2VFlLmyViO0/n3MyQNde3UHjAdf8/DQRGZbawmmfgH8wj4BOjP5usaRPOQE6lAO4R6mG+zznjIbd5EbjlDWOAu7UMHYBLCVDfQMlALPTgxm8YuA5n4erbDcwGOvGSBZ3kwqA192RwFbWzTXu8QN27LQ3h8b8HGt9AJFJoPoLAWDMDt5/ZnUqiuswBqpJkivQqclr6hgXWctFRVAK0kDdEQmPFcg1xxmGxXRKwoTnRGvJR2zyD4xrz3AiAcS6zyW1z0AxOZt1YrhOSj63T0AK/efS6FHNKKZ8/0Q=',
body: '{     "id": 3301789948,     "repositoryName": "test_repo_examples",     "repositoryOwner": "[redacted]",     "eventType": "check_run",     "installationId": 16020721 }',
attributes: {
ApproximateReceiveCount: '26',
SentTimestamp: '1628691656000',
SequenceNumber: '18863689137645552896',
MessageGroupId: '3301789948',
SenderId: 'AROAX64G5H7LJB5BAFLYZ:dev-webhook',
MessageDeduplicationId: '4198aee0b7624a61d60c276a7dac96185adccecc853ea39b554a341ce8040433',
ApproximateFirstReceiveTimestamp: '1628691686050'
},
messageAttributes: {},
md5OfBody: '784c3f35f97488a57ed023d22f6532d5',
eventSource: 'aws:sqs',
eventSourceARN: 'arn:aws:sqs:us-east-1:547354394582:dev-queued-builds.fifo',
awsRegion: 'us-east-1'
}
]
}
2021-08-11T15:36:30.415Z	28287858-b79a-57a8-92a9-21d54736de72	DEBUG
```

Next, the 404 from the HTTP GET from dev-sync-up lambda to GitHub:

```
2021-08-11T15:36:30.788Z	28287858-b79a-57a8-92a9-21d54736de72	ERROR	RequestError [HttpError]: Not Found
    at /var/task/index.js:2779:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 11 Aug 2021 15:36:30 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': '8EC2:1BE9:5F61C:10E84F:6113EE7E',
    'x-ratelimit-limit': '15000',
    'x-ratelimit-remaining': '14941',
    'x-ratelimit-reset': '1628696190',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '59',
    'x-xss-protection': '0'
  },
  request: {
    method: 'GET',
    url: 'https://api.github.com/repos/[REDACTED]/test_repo_examples/check-runs/3301789948',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.2.0 octokit-core.js/3.2.4 Node.js/12.22.3 (linux; x64)',
      authorization: 'token [REDACTED]'
    },
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/checks#get-a-check-run'
}
```

Is there a troubleshooting path for this situation? And should this be 'handled' somehow by the automation? Happy to provide more info. Thanks in advance.

UPDATE: The version of this module used is 0.13.1.

UPDATE II: I have 3 'in-flight messages' in SQS for the queue associated with the 'scale-up' lambda. What that means is that the application that is consuming the messages read the message, but did no further processing on the message (i.e. deleting it), so the message is added back to the queue after a timeout. I think what's happening then is that the 'scale-up' Lambda app is then consuming the message, erroring out, therefore not deleting it, which then triggers the cycle again. Hope that makes sense.

**Comment by boldandbusted** [comment]
FWIW, I solved this by doing the following in the AWS Console:
* Find the Lambda SQS Trigger associated with the 'scale-up' Lambda.
* Disabling the trigger
* Waiting 3 minutes for the [SQS Visibility Timeout](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html) to expire
* Purge the queue of the now-visible messages.
* Re-enable the Lambda SQS Trigger disabled above.

Hope this helps someone else who encounters this problem.

**Comment by mcaulifn** [comment]
Setting https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue#message_retention_seconds to something shorter than 4 days would help these scenarios.
