### ISSUE TITLE
[lambda scale up] Cannot decrypt 

### ISSUE THREAD

**Issue by PavelSusloparov** [philips-labs/terraform-aws-github-runner#1153]
Trying to upgrade from 0.13.0 to 0.18.1.

Scale up lambda Cloud Watch logs show:
```
e32185e1-05a2-56c3-ae86-dc48d658b6f0	ERROR	Error: Cannot decrypt.    at Object.<anonymous> (/var/task/index.js:58070:19)    at Generator.next (<anonymous>)    at fulfilled (/var/task/index.js:58040:58) | 2021-09-01T19:17:35.898Z e32185e1-05a2-56c3-ae86-dc48d658b6f0 ERROR Error: Cannot decrypt. at Object.<anonymous> (/var/task/index.js:58070:19) at Generator.next (<anonymous>) at fulfilled (/var/task/index.js:58040:58)
-- | --
```

My configuration:
```
locals {
  environment = "ctprd-github-actions-runners"
  aws_region  = "us-east-2"
}

resource "random_password" "random" {
  length = 28
}

resource "aws_kms_key" "github" {
  is_enabled          = true
  description         = "kms key used encrypt decrypt github selfhosted runner"
  enable_key_rotation = true
}

resource "aws_iam_service_linked_role" "spot" {
  aws_service_name = "spot.amazonaws.com"
}

module "runners" {
  source = "git::https://github.com/philips-labs/terraform-aws-github-runner.git?ref=v0.18.1"

  aws_region = local.aws_region
  vpc_id         = data.terraform_remote_state.vpc.outputs.vpc_id
  subnet_ids = data.terraform_remote_state.vpc.outputs.private_subnets

  environment = local.environment
  tags = {
    "Project" = "GitHub Actions Self-Hosted Runners"
    Terraform = "True"
  }

  github_app = {
    key_base64     = data.sops_file.this.data["github_app_key_base64"]
    id             = data.sops_file.this.data["github_app_id"]
    client_id      = data.sops_file.this.data["github_app_client_id"]
    client_secret  = data.sops_file.this.data["github_app_client_secret"]
    webhook_secret = random_password.random.result
  }

  instance_type                     = "m5.large"
  webhook_lambda_zip                = "lambdas-download/webhook.zip"
  runner_binaries_syncer_lambda_zip = "lambdas-download/runner-binaries-syncer.zip"
  runners_lambda_zip                = "lambdas-download/runners.zip"
  enable_organization_runners       = true
  runner_extra_labels               = "terraform, autoscale"

  # enable access to the runners via SSM
  enable_ssm_on_runners = true

  kms_key_arn     = aws_kms_key.github.arn

  block_device_mappings = {
    volume_size = 100
  }

  minimum_running_time_in_minutes = 2

  # idle config to tell how many instances and when to run
  idle_config = [
    {
      cron     = "* * * * * *"
      timeZone = "America/New_York"
      # min number of instances
      idleCount = 30
    }
  ]
  # max number of instances for scalling up
  runners_maximum_count = 255
}

data "terraform_remote_state" "vpc" {
  backend = "s3"
  config = {
    bucket       = "omitted"
    key          = "omitted"
    region       = "us-east-1"
    role_arn     = "omitted"
    session_name = "omitted"
  }
}

data "sops_file" "this" {
  source_file = "omitted"
  input_type  = "json"
}
```

**Comment by PavelSusloparov** [comment]
I forgot to download newer lambdas zips. With the matching lambdas versions, it works.
