### ISSUE TITLE
Spot-instance runners get terminated despite idle_config

### ISSUE THREAD

**Issue by teodor-daskalov** [philips-labs/terraform-aws-github-runner#1226]
Hi,

In my company we have implemented your solution and it is working great so far, so thanks a million for creating this!

However, we did run into a problem just today. It looks as if the module ignores the `idle_config` setting and at a certain time decides to terminate all instances. Our config is the following:

```
  idle_config = [{
    cron      = "* * * * * *"
    timeZone  = "Europe/Zurich"
    idleCount = 2
  }]
```

It was fine during the weekend (although I see in our list of runners some "Offline" instances, perhaps they didn't de-register properly before getting terminated?) but this morning I saw that both idle instances got terminated. 

I tried checking cloudwatch logs, but as my AWS skills are still a bit limited, I didn't see anything out of the ordinary in the scale-down lambda logs. Maybe I'm not checking in the right place. Could you advise on this, please? It would be much appreciated.

Oh, and another question: where exactly to switch from spot-instances to on-demand instances? A colleague of mine suggested to use on-demand instances, since there might be insufficient capacity in the datacenter and someone else might be giving a higher price for their spot instances, so ours are getting terminated. I saw the parameter `market_options` in the runners module, but I'm not sure which value to pass to it. My Terraform skills are not that advanced either. 

Thanks in advance for your reply!

BR,
Teo

**Comment by teodor-daskalov** [comment]
Found the reason why they were getting shut-down:
```
2021-10-04T09:06:42.986Z 0ef655b7-1e7a-5be7-a9c3-0c63d8333d45 ERROR InsufficientInstanceCapacity: There is no Spot capacity available that matches your request.
 at Request.extractError (/var/task/index.js:75719:35)
 at Request.callListeners (/var/task/index.js:74414:20)
 at Request.emit (/var/task/index.js:74386:10)
 at Request.emit (/var/task/index.js:73020:14)
 at Request.transition (/var/task/index.js:72354:10)
 at AcceptorStateMachine.runTo (/var/task/index.js:79372:12)
 at /var/task/index.js:79384:10
 at Request.<anonymous> (/var/task/index.js:72370:9)
 at Request.<anonymous> (/var/task/index.js:73022:12)
 at Request.callListeners (/var/task/index.js:74424:18) {
 code: 'InsufficientInstanceCapacity',
 time: 2021-10-04T09:06:42.986Z,
 requestId: 'c714cc97-03d7-4fd7-b4c2-e59ea28f0320',
 statusCode: 500,
 retryable: true
}
```

So we switched to on-demand instances and now it's good!

What is the default limit for the amount of running github runners? I couldn't find a variable related to this in the module.

**Comment by teodor-daskalov** [comment]
Everything is looking good for now, I will close the issue and re-open if necessary. Thanks!
