### ISSUE TITLE
gh-ci-scale-up error

### ISSUE THREAD

**Issue by b-jam** [philips-labs/terraform-aws-github-runner#1380]
Heya,

I've followed the instructions on the module, got all the infra setup + github app + offline runner on my machine, ran `config.sh` .
Added the webhook + secret into github app after running the module. Installed the app organisation wide, with `workflow-job` subscription to events.

I'm getting the following error from the gs-ci-scale-up lambda.
On github actions it just hangs, saying 
```
Can't find any online and idle self-hosted runner in the current repository, account/organization that matches the required labels: 'self-hosted'
Waiting for a self-hosted runner to pickup this job...
```

Am I missing something? If I actually `run.sh` the local runner then it runs

And the error in cloudwatch logs for gh-ci-scale-up:

```
2021-11-05T03:56:45.174Z	ERROR	RequestError [HttpError]: A JSON web token could not be decoded

    at /var/task/index.js:43611:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async getInstallationAuthentication (/var/task/index.js:43259:7) {
  status: 401,
  response: {
    url: 'https://api.github.com/app/installations/20378940/access_tokens',
    status: 401,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
      connection: 'close',
      'content-length': '102',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Fri, 05 Nov 2021 03:56:45 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-media-type': 'github.v3; param=machine-man-preview; format=json',
      'x-github-request-id': '[REDACTED]',
      'x-xss-protection': '0'
    },
    data: {
      message: 'A JSON web token could not be decoded',
      documentation_url: 'https://docs.github.com/rest'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/app/installations/20378940/access_tokens',
    headers: {
      accept: 'application/vnd.github.machine-man-preview+json',
      'user-agent': 'octokit-auth-app.js/3.6.0 Node.js/14.17.4 (linux; x64)',
      authorization: 'bearer [REDACTED]',
      'content-length': 0
    }
  }
}```

**Comment by npalm** [comment]
Looks like your secrets for the app are not configured right. Please double check you have configured the SSH key right.  You can load the secret in a TF var as follow for example:

```bash
export TF_VAR_github_app_key_base64=$(cat private_key.pem | base64)
```

**Comment by b-jam** [comment]
Ah, right secret, wrong app id. Cheers
