### ISSUE TITLE
Issue setting up ARM runners

### ISSUE THREAD

**Issue by Fgerthoffert** [philips-labs/terraform-aws-github-runner#2800]
Hi,

I'm trying to set up ARM runners (Ubuntu), using a multi-runner setup and ephemeral runners.
Currently on `v2.0.0-next.7`

I do see the EC2 instance starting and the event being processed by the lamba.

Cloudwatch webhook log:
```
2022-12-27 15:11:49.635  INFO  [webhook:7b53dc51-68bc-4157-b28b-0cf3f8e2e90f index.js:92766  handleWorkflowJob] Successfully queued job for Jahia/sandbox to the queue https://sqs.eu-west-1.amazonaws.com/602599330770/github-multi-runner-linux-arm64-queued-builds.fifo 
{
    "event": "workflow_job",
    "repository": "Jahia/sandbox",
    "action": "queued",
    "name": "Integration Tests ARM64",
    "status": "queued",
    "workflowJobId": 10320857794,
    "started_at": "2022-12-27T15:11:48Z",
    "completed_at": null,
    "conclusion": null
}
```

But then in the runner log, I see the following:
```
[2022-12-27 15:17:27Z ERR  GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/paL7vYQ7ZmTSxjNblisOPNLOcIfSe305oBAC33zIngj5bTrc47/_apis/distributedtask/pools/1/messages?sessionId=ac2c26bc-f175-45eb-b900-3d045b683852&status=Online&runnerVersion=2.300.2 failed. HTTP Status: Forbidden, AFD Ref: Ref A: 55CB5E5D17254A61B7088C4D3A1D687C Ref B: DB3EDGE2508 Ref C: 2022-12-27T15:17:27Z

[2022-12-27 15:17:27Z ERR  MessageListener] Catch exception during get next message.

[2022-12-27 15:17:27Z ERR  MessageListener] GitHub.DistributedTask.WebApi.AccessDeniedException: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.
   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)

[2022-12-27 15:17:27Z INFO MessageListener] Non-retriable exception: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.
```

I have the same job using x86 runners, which are running properly.

The ARM runner config is:
```
    "linux-arm64" = {
      matcherConfig : {
        # labelMatchers = [["self-hosted", "linux", "arm64", "ubuntu-2204"]]
        # Doing so effectively disables the runner        
        labelMatchers = [["self-hosted", "linux", "arm64", "ubuntu-2204"]]
        exactMatch    = true
      }
      fifo                = true
      delay_webhook_event = 0
      redrive_build_queue = {
        enabled         = false
        maxReceiveCount = null
      }
      runner_config = {
        runner_os                       = "linux"
        runner_architecture             = "arm64"
        runner_extra_labels             = "arm"
        runner_run_as                   = "ubuntu"
        enable_ssm_on_runners           = true
        create_service_linked_role_spot = true
        instance_types                  = ["t4g.large", "c6g.large"]
        runners_maximum_count           = 5
        scale_down_schedule_expression  = "cron(* * * * ? *)"
        enable_ephemeral_runners        = true
        enabled_userdata                = false
        enable_organization_runners     = true

        # configure your pre-built AMI
        ami_filter = {
          name = ["github-runner-ubuntu-jammy-arm64-2022*"]
        }
        ami_owners = [data.aws_caller_identity.current.account_id] 

        userdata_template = "./templates/user-data.sh"

        block_device_mappings = [{
          # Set the block device name for Ubuntu root device
          device_name           = "/dev/sda1"
          delete_on_termination = true
          volume_type           = "gp3"
          volume_size           = 30
          encrypted             = true
          iops                  = null
          throughput            = null
          kms_key_id            = null
          snapshot_id           = null
        }]
        runner_log_files = [
          {
            log_group_name   = "syslog"
            prefix_log_group = true
            file_path        = "/var/log/syslog"
            log_stream_name  = "{instance_id}"
          },
          {
            log_group_name   = "user_data"
            prefix_log_group = true
            file_path        = "/var/log/user-data.log"
            log_stream_name  = "{instance_id}/user_data"
          },
          {
            log_group_name   = "runner"
            prefix_log_group = true
            file_path        = "/opt/actions-runner/_diag/Runner_**.log",
            log_stream_name  = "{instance_id}/runner"
          }
        ]
      }
    },
```

The ubuntu ARM64 packer file:
```
packer {
  required_plugins {
    amazon = {
      version = ">= 0.0.2"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "runner_version" {
  description = "The version (no v prefix) of the runner software to install https://github.com/actions/runner/releases"
  type        = string
  default     = "2.300.2"
}

variable "region" {
  description = "The region to build the image in"
  type        = string
  default     = "eu-west-1"
}

variable "security_group_id" {
  description = "The ID of the security group Packer will associate with the builder to enable access"
  type        = string
  default     = null
}

variable "subnet_id" {
  description = "If using VPC, the ID of the subnet, such as subnet-12345def, where Packer will launch the EC2 instance. This field is required if you are using an non-default VPC"
  type        = string
  default     = null
}

variable "associate_public_ip_address" {
  description = "If using a non-default VPC, there is no public IP address assigned to the EC2 instance. If you specified a public subnet, you probably want to set this to true. Otherwise the EC2 instance won't have access to the internet"
  type        = string
  default     = null
}

variable "instance_type" {
  description = "The instance type Packer will use for the builder"
  type        = string
  default     = "t4g.medium"
}

variable "root_volume_size_gb" {
  type    = number
  default = 30
}

variable "ebs_delete_on_termination" {
  description = "Indicates whether the EBS volume is deleted on instance termination."
  type        = bool
  default     = true
}

variable "global_tags" {
  description = "Tags to apply to everything"
  type        = map(string)
  default     = {}
}

variable "ami_tags" {
  description = "Tags to apply to the AMI"
  type        = map(string)
  default     = {}
}

variable "snapshot_tags" {
  description = "Tags to apply to the snapshot"
  type        = map(string)
  default     = {}
}

variable "custom_shell_commands" {
  description = "Additional commands to run on the EC2 instance, to customize the instance, like installing packages"
  type        = list(string)
  default     = []
}

source "amazon-ebs" "githubrunner" {
  ami_name                    = "github-runner-ubuntu-jammy-arm64-${formatdate("YYYYMMDDhhmm", timestamp())}"
  instance_type               = var.instance_type
  region                      = var.region
  security_group_id           = var.security_group_id
  subnet_id                   = var.subnet_id
  associate_public_ip_address = var.associate_public_ip_address

  source_ami_filter {
    filters = {
      name                = "*/ubuntu-jammy-22.04-arm64-server-*"
      root-device-type    = "ebs"
      virtualization-type = "hvm"
    }
    most_recent = true
    owners      = ["099720109477"]
  }
  ssh_username = "ubuntu"
  tags = merge(
    var.global_tags,
    var.ami_tags,
    {
      OS_Version    = "ubuntu-jammy"
      Release       = "Latest"
      Base_AMI_Name = "{{ .SourceAMIName }}"
  })
  snapshot_tags = merge(
    var.global_tags,
    var.snapshot_tags,
  )

  launch_block_device_mappings {
    device_name           = "/dev/sda1"
    volume_size           = "${var.root_volume_size_gb}"
    volume_type           = "gp3"
    delete_on_termination = "${var.ebs_delete_on_termination}"
  }
}

build {
  name = "githubactions-runner"
  sources = [
    "source.amazon-ebs.githubrunner"
  ]
  provisioner "shell" {
    environment_vars = [
      "DEBIAN_FRONTEND=noninteractive"
    ]
    inline = concat([
      "sudo apt-get -y update",
      "sudo apt-get -y install ca-certificates curl gnupg lsb-release",
      "sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg",
      "echo deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null",
      "sudo apt-get -y update",
      "sudo apt-get -y install docker-ce docker-ce-cli containerd.io jq git unzip",
      "sudo systemctl enable containerd.service",
      "sudo service docker start",
      "sudo usermod -a -G docker ubuntu",
      "sudo curl -f https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/arm64/latest/amazon-cloudwatch-agent.deb -o amazon-cloudwatch-agent.deb",
      "sudo dpkg -i amazon-cloudwatch-agent.deb",
      "sudo systemctl restart amazon-cloudwatch-agent",
      "sudo curl -f https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip -o awscliv2.zip",
      "unzip awscliv2.zip",
      "sudo ./aws/install",
    ], var.custom_shell_commands)
  }

  provisioner "file" {
    content = templatefile("../install-runner.sh", {
      install_runner = templatefile("../../modules/runners/templates/install-runner.sh", {
        ARM_PATCH                       = ""
        S3_LOCATION_RUNNER_DISTRIBUTION = ""
        RUNNER_ARCHITECTURE             = "arm64"
      })
    })
    destination = "/tmp/install-runner.sh"
  }

  provisioner "shell" {
    environment_vars = [
      "RUNNER_TARBALL_URL=https://github.com/actions/runner/releases/download/v${var.runner_version}/actions-runner-linux-arm64-${var.runner_version}.tar.gz"
    ]
    inline = [
      "sudo chmod +x /tmp/install-runner.sh",
      "echo ubuntu | tee -a /tmp/install-user.txt",
      "sudo RUNNER_ARCHITECTURE=arm64 RUNNER_TARBALL_URL=$RUNNER_TARBALL_URL /tmp/install-runner.sh",
      "echo ImageOS=ubuntu22 | tee -a /opt/actions-runner/.env"
    ]
  }

  provisioner "file" {
    content = templatefile("../start-runner.sh", {
      start_runner = templatefile("../../modules/runners/templates/start-runner.sh", {})
    })
    destination = "/tmp/start-runner.sh"
  }

  provisioner "shell" {
    inline = [
      "sudo mv /tmp/start-runner.sh /var/lib/cloud/scripts/per-boot/start-runner.sh",
      "sudo chmod +x /var/lib/cloud/scripts/per-boot/start-runner.sh",
    ]
  }

}
```
I had to comment out these line in order to build for ubuntu on ARM64: https://github.com/philips-labs/terraform-aws-github-runner/blob/801e01f290407975aea11b85e44ac9743f9173cb/modules/runners/templates/install-runner.sh#L45-L47

<img width="999" alt="Screen Shot 2022-12-27 at 16 32 57" src="https://user-images.githubusercontent.com/5667028/209688201-ddba221c-a3b0-4a3c-98bc-ff96a2741011.png">

Any clue what I could be doing wrong?

**Comment by npalm** [comment]
Had a quick look, bu I have no clue. Your config looks OK. Are you not pre-loading the runner agent into the AMI? We have since two weeks an unbuntu22.04 ARM runner live. Runs without an issue. I will try to check quickly the packages we installed. I have used the same setup as GitHub to build AMI, but strips it to a minimum.

**Comment by Fgerthoffert** [comment]
Yes, the runners are pre-loaded in the AMI.

The runner in the ARM instance does seem to start properly, I was seeing logs such as:

```
[2022-12-27 15:13:06Z INFO MessageListener] {
  "AgentId": 50978,
  "AgentName": "i-0902707468f0d90a8",
  "PoolId": 1,
  "PoolName": "Default",
  "Ephemeral": true,
  "ServerUrl": "https://pipelines.actions.githubusercontent.com/paL7vYQ7ZmTSxjNblisOPNLOcIfSe305oBAC33zIngj5bTrc47",
  "GitHubUrl": "https://github.com/Jahia",
  "WorkFolder": "_work"
}
```

The only thing that did look wrong in these log messages are the bunch of errors messages.

Looking a bit closer though, I noticed there is 4mn between the last "normal" log and the first error. I'm not sure what it is related to.

```
[2022-12-27 15:13:09Z INFO JobDispatcher] Set runner/worker IPC timeout to 30 seconds.
[2022-12-27 15:17:27Z ERR  GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/paL7vYQ7ZmTSxjNblisOPNLOcIfSe305oBAC33zIngj5bTrc47/_apis/distributedtask/pools/1/messages?sessionId=ac2c26bc-f175-45eb-b900-3d045b683852&status=Online&runnerVersion=2.300.2 failed. HTTP Status: Forbidden, AFD Ref: Ref A: 55CB5E5D17254A61B7088C4D3A1D687C Ref B: DB3EDGE2508 Ref C: 2022-12-27T15:17:27Z
```

**Comment by Fgerthoffert** [comment]
Actually, this might not be where the issue is, I might be missing something in the setup.

If I take this workflow:
```
name: Runner test
on: 
  workflow_dispatch:
jobs:
  integration-tests:
    name: Runner test
    runs-on: self-hosted
    steps:
      - name: Displaying arch
        shell: bash
        run: |
          uname -s
          uname -m
```

It is sometimes picked-up by an X86 runner:
<img width="1138" alt="Screen Shot 2022-12-29 at 08 44 03" src="https://user-images.githubusercontent.com/5667028/209919737-bd850ed5-6d7d-4c8f-acf6-3616be850eae.png">

Sometimes by an ARM runner:
<img width="1153" alt="Screen Shot 2022-12-29 at 08 47 14" src="https://user-images.githubusercontent.com/5667028/209920023-ca09d32e-2d2d-4184-afdb-9a5a106f6194.png">

With the following logs in the webhook group:
```
2022-12-29 07:42:12.944  DEBUG [webhook:b2b5d570-c3bd-4563-ad6a-ac785da4bea2 index.js:92796  canRunJob] Received workflow job event with labels: '["self-hosted"]'. The event does match the runner labels: 'self-hosted,linux,arm64,ubuntu-2204' {
    "event": "workflow_job",
    "repository": "Jahia/sandbox",
    "action": "queued",
    "name": "Runner test",
    "status": "queued",
    "workflowJobId": 10346087188,
    "started_at": "2022-12-29T07:42:10Z",
    "completed_at": null,
    "conclusion": null
} 

```
I understand this is [the expected behavior](https://github.com/philips-labs/terraform-aws-github-runner/tree/main/modules/multi-runner#the-catch).

Now if I get more specific with labels in the "runs-on":

```
name: Runner test
on: 
  workflow_dispatch:
jobs:
  integration-tests:
    name: Runner test
    runs-on: [self-hosted, linux, x64, ubuntu-latest]
    steps:
      - name: Displaying arch
        shell: bash
        run: |
          uname -s
          uname -m
```

I see the following in the webhook logs:
```

2022-12-29 07:53:39.939  DEBUG [webhook:dbbcee07-7667-4b48-a478-c1d52e0d33bb index.js:92796  canRunJob] Received workflow job event with labels: '["self-hosted","linux","x64","ubuntu-latest"]'. The event does NOT match the runner labels: 'self-hosted,linux,arm64,ubuntu-2204' {
    "event": "workflow_job",
    "repository": "Jahia/sandbox",
    "action": "queued",
    "name": "Runner test X86",
    "status": "queued",
    "workflowJobId": 10346184978,
    "started_at": "2022-12-29T07:53:38Z",
    "completed_at": null,
    "conclusion": null
} 
2022-12-29 07:53:39.940  DEBUG [webhook:dbbcee07-7667-4b48-a478-c1d52e0d33bb index.js:92796  canRunJob] Received workflow job event with labels: '["self-hosted","linux","x64","ubuntu-latest"]'. The event does match the runner labels: 'self-hosted,linux,x64,ubuntu-latest,self-hosted,linux,x64,ubuntu-2204' {
    "event": "workflow_job",
    "repository": "Jahia/sandbox",
    "action": "queued",
    "name": "Runner test X86",
    "status": "queued",
    "workflowJobId": 10346184978,
    "started_at": "2022-12-29T07:53:38Z",
    "completed_at": null,
    "conclusion": null
} 

```

The job is being picked-up properly:
<img width="1146" alt="Screen Shot 2022-12-29 at 08 56 02" src="https://user-images.githubusercontent.com/5667028/209920941-f986f25a-bc44-453c-8ba7-d6fae7500cb6.png">

But then with this workflow:
```
name: Runner test ARM
on: 
  workflow_dispatch:
jobs:
  integration-tests:
    name: Runner test ARM
    runs-on: [self-hosted, linux, arm64, ubuntu-2204]
    steps:
      - name: Displaying arch
        shell: bash
        run: |
          uname -s
          uname -m
```

I do see such logs:
```
2022-12-29 07:56:39.819  DEBUG [webhook:30175201-b902-4b0d-97db-be060fc2be0b index.js:92796  canRunJob] Received workflow job event with labels: '["self-hosted","linux","arm64","ubuntu-2204"]'. The event does match the runner labels: 'self-hosted,linux,arm64,ubuntu-2204' {
    "event": "workflow_job",
    "repository": "Jahia/sandbox",
    "action": "queued",
    "name": "Runner test ARM",
    "status": "queued",
    "workflowJobId": 10346209041,
    "started_at": "2022-12-29T07:56:38Z",
    "completed_at": null,
    "conclusion": null
} 
```

But the job is not being picked up.
<img width="1152" alt="Screen Shot 2022-12-29 at 08 58 16" src="https://user-images.githubusercontent.com/5667028/209921179-52af6306-981b-45fd-8373-2b7e0cb55ee2.png">

I guess the issue is somewhere around the runs-on label

**Comment by npalm** [comment]
But when checking the runner start script, do you see the runner started healthy? Printing the GitHub Action ASCII art? Our setup is ephemeral, so runners are running shortly. But so far I haven't see an issue.

Some installation details for my packer scripts that differs a bit from yours:

common
```
apt-get install -y apt-transport-https ca-certificates curl software-properties-common
apt-get -yq dist-upgrade
```

docker
```
#!/bin/bash -e
################################################################################
##  File:  docker.sh
##  Desc:  Installs docker onto the image
################################################################################

# Source the helpers for use with the script
source $HELPER_SCRIPTS/install.sh
source $HELPER_SCRIPTS/os.sh

# https://docs.docker.com/engine/install/ubuntu/
apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update
apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Docker daemon takes time to come up after installing
sleep 10
docker info

# Install amazon-ecr-credential-helper
aws_latest_release_url="https://api.github.com/repos/awslabs/amazon-ecr-credential-helper/releases/latest"
aws_helper_url=$(getLatestReleaseDistributionBody "awslabs/amazon-ecr-credential-helper" "linux-$(getArchitectureLabelArm64amd64)")

download_with_retries "$aws_helper_url" "/usr/bin" docker-credential-ecr-login
chmod +x /usr/bin/docker-credential-ecr-login

# allow docker to be run without sudo
usermod -aG docker ubuntu

```

git
```
# Source the helpers for use with the script
source $HELPER_SCRIPTS/install.sh

GIT_REPO="ppa:git-core/ppa"
GIT_LFS_REPO="https://packagecloud.io/install/repositories/github/git-lfs"

## Install git
add-apt-repository $GIT_REPO -y
apt-get update
apt-get install git -y
git --version

# Install git-lfs
curl -s $GIT_LFS_REPO/script.deb.sh | bash
apt-get install -y git-lfs

# Remove source repo's
add-apt-repository --remove $GIT_REPO
rm /etc/apt/sources.list.d/github_git-lfs.list

# Document apt source repo's
echo "git-core $GIT_REPO" >> $HELPER_SCRIPTS/apt-sources.txt
echo "git-lfs $GIT_LFS_REPO" >> $HELPER_SCRIPTS/apt-sources.txt

```

runner
```
# Source the helpers for use with the script
source $HELPER_SCRIPTS/os.sh

## install the runner

# echo "Creating actions-runner directory for the GH Action installation"
mkdir -p /opt/actions-runner
cd /opt/actions-runner

# Download the latest runner package
file_name="actions-runner.tar.gz"
runner_version=$(curl -s https://api.github.com/repos/actions/runner/releases/latest | jq -r ".tag_name")
download_url=$(curl -s https://api.github.com/repos/actions/runner/releases/tags/$runner_version | jq -r ".assets[] | select(.name | test(\"-linux-$(getArchitectureLabelArm64x64)-[0-9.]*.((tar.gz)|(zip))\")) | .browser_download_url")

echo "Downloading the GH Action runner from ${download_url} to $file_name"
curl -o $file_name -L "${download_url}"

echo "Un-tar action runner"
tar xzf ./$file_name
echo "Delete tar file"
rm -rf $file_name
```

As you see quite standard. See not a main diff to yours.

**Comment by Fgerthoffert** [comment]
Apologies, it seems we were cross-posting :) if you can look at my comment above
