### ISSUE TITLE
Unable to start runner on EC2 instance

### ISSUE THREAD

**Issue by jkruse14** [philips-labs/terraform-aws-github-runner#2966]
The user-script runs fine until I get to the Authentication step when running the config script, it just hangs:

```
<13>Feb 15 14:36:54 user-data: --------------------------------------------------------------------------------
<13>Feb 15 14:36:54 user-data: |        ____ _ _   _   _       _          _        _   _                      |
<13>Feb 15 14:36:54 user-data: |       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
<13>Feb 15 14:36:54 user-data: |      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
<13>Feb 15 14:36:54 user-data: |      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
<13>Feb 15 14:36:54 user-data: |       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
<13>Feb 15 14:36:54 user-data: |                                                                              |
<13>Feb 15 14:36:54 user-data: |                       Self-hosted runner registration                        |
<13>Feb 15 14:36:54 user-data: |                                                                              |
<13>Feb 15 14:36:54 user-data: --------------------------------------------------------------------------------
<13>Feb 15 14:36:54 user-data: 
<13>Feb 15 14:36:54 user-data: # Authentication
<13>Feb 15 14:36:54 user-data: 
<13>Feb 15 14:46:55 user-data: The HTTP request timed out after 00:01:00.
```

I've seen the _diag logs requested in other issues, so here is the last bit of it (immediately following the logo printout):
```
2023-02-15 15:20:23Z INFO ConfigurationManager] ConfigureAsync
[2023-02-15 15:20:23Z INFO CommandSettings] Flag 'generateServiceConfig': 'False'
[2023-02-15 15:20:23Z INFO ConfigurationStore] IsConfigured()
[2023-02-15 15:20:23Z INFO ConfigurationStore] IsConfigured: False
[2023-02-15 15:20:23Z INFO ConfigurationManager] Is configured: False
[2023-02-15 15:20:23Z INFO CommandSettings] Arg 'url': 'https://github.com/DoosanBobcatSandbox'
[2023-02-15 15:20:23Z INFO CommandSettings] Remove url from Arg dictionary.
[2023-02-15 15:20:23Z INFO CommandSettings] Arg 'token': '***'
[2023-02-15 15:20:23Z INFO CommandSettings] Remove token from Arg dictionary.
[2023-02-15 15:20:24Z INFO ConfigurationManager] Http response code: OK from 'POST https://api.github.com/actions/runner-registration' (4778:7458:1BDA4C9:3907870:63ECF838)
[2023-02-15 15:20:24Z INFO ConfigurationManager] cred retrieved via GitHub auth
[2023-02-15 15:20:24Z INFO RunnerServer] EstablishVssConnection
[2023-02-15 15:20:24Z INFO RunnerServer] Establish connection with 100 seconds timeout.
[2023-02-15 15:20:24Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-02-15 15:20:24Z INFO RunnerServer] EstablishVssConnection
[2023-02-15 15:20:24Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-02-15 15:20:24Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-02-15 15:20:24Z INFO RunnerServer] EstablishVssConnection
[2023-02-15 15:20:24Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-02-15 15:20:24Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-02-15 15:21:24Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/WwH58rYm16yb81FWQzkSnD8S3sUx9xj40RpAMo2ZqlfENPswJB/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-02-15 15:21:24Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/WwH58rYm16yb81FWQzkSnD8S3sUx9xj40RpAMo2ZqlfENPswJB/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-02-15 15:21:24Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-02-15 15:21:24Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-02-15 15:21:24Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-02-15 15:21:24Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
```

I got more information from the _daig log file after another run:
```
2023-02-15 15:55:02Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-02-15 15:56:02Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/WwH58rYm16yb81FWQzkSnD8S3sUx9xj40RpAMo2ZqlfENPswJB/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-02-15 15:56:02Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-02-15 15:56:02Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/WwH58rYm16yb81FWQzkSnD8S3sUx9xj40RpAMo2ZqlfENPswJB/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-02-15 15:56:02Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-02-15 15:56:02Z INFO CommandSettings] Flag 'unattended': 'True'
[2023-02-15 15:56:02Z ERR  Runner] System.TimeoutException: The HTTP request timed out after 00:01:00.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.RunnerService.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)
   at GitHub.Runner.Common.RunnerServer.ConnectAsync(Uri serverUrl, VssCredentials credentials)
   at GitHub.Runner.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
   at GitHub.Runner.Listener.Runner.ExecuteCommand(CommandSettings command)
[2023-02-15 15:56:02Z ERR  Runner] #####################################################
[2023-02-15 15:56:02Z ERR  Runner] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2023-02-15 15:56:02Z ERR  Terminal] WRITE ERROR: The HTTP request timed out after 00:01:00.
[2023-02-15 15:56:02Z INFO Listener] Runner execution has finished with return code 1
```

cloud-init-outp.log also says the user-data script failed:

```
Feb 15 15:56:02 cloud-init[1222]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
```

When I curl the pipleines.actions.githubuserconetent.com URL above, it gives a 200 immediately with a lot of output.

Does anyone have any ideas as to why it might be hanging or how I should proceed?

I've confirmed HTTPS access is granted on all ports in my SGs and have followed the flow logs to see traffic moving from this vpc to our "internet" vpc and back via a transit gateway. As I mentioned above, I can `curl` resources outside of our network. Is SSH used at all in the registration or setup process? From what I've read, HTTPS is the only protocol used.

**Comment by jkruse14** [comment]
I just found the answer and tested. The issue seems to be with IPv6. I removed the IPv6 assignment from the runner as it was starting up and everything ran fine.

I created subnets without IPv6 (setting assign_ipv6_address_on_creation to false) and the issue was then resolved and authentication took place.

Side note: originally, amazon-linux-extras just hung during the start up when trying to install docker. This resolved that issue as well.

**Comment by CalvinLac** [comment]
> I just found the answer and tested. The issue seems to be with IPv6. I removed the IPv6 assignment from the runner as it was starting up and everything ran fine.
> 
> I created subnets without IPv6 (setting assign_ipv6_address_on_creation to false) and the issue was then resolved and authentication took place.
> 
> Side note: originally, amazon-linux-extras just hung during the start up when trying to install docker. This resolved that issue as well.

Hi @jkruse14, could you share how you swapped out the creation of the internet gateway for a transit gateway? This is the exact issue I'm facing and can't seem to find much direction on how it's done. Thanks!

**Comment by jkruse14** [comment]
> Hi @jkruse14, could you share how you swapped out the creation of the internet gateway for a transit gateway? This is the exact issue I'm facing and can't seem to find much direction on how it's done. Thanks!

@CalvinLac - I'm sorry, I'm not sure what you're asking, I only updated a setting on the subnet configuration so it only used ipv4. For a full fix, I created subnets named IPV4Only (so we know exactly what they are and why) and deploy the runners in those subnets.
