### ISSUE TITLE
Building the AWS Ubuntu image fails

### ISSUE THREAD

**Issue by bjonnh-work** [philips-labs/terraform-aws-github-runner#3103]
Trying to build the ubuntu pre-built image, I get the following error:
```
==> githubactions-runner.amazon-ebs.githubrunner: E: Could not open file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_jammy_main_cnf_Commands-amd64 - open (2: No such file or directory)
==> githubactions-runner.amazon-ebs.githubrunner: Traceback (most recent call last):
==> githubactions-runner.amazon-ebs.githubrunner:   File "/usr/lib/cnf-update-db", line 32, in <module>
==> githubactions-runner.amazon-ebs.githubrunner:     col.create(db)
==> githubactions-runner.amazon-ebs.githubrunner:   File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 95, in create
==> githubactions-runner.amazon-ebs.githubrunner:     self._fill_commands(con)
==> githubactions-runner.amazon-ebs.githubrunner:   File "/usr/lib/python3/dist-packages/CommandNotFound/db/creator.py", line 144, in _fill_commands
==> githubactions-runner.amazon-ebs.githubrunner:     raise subprocess.CalledProcessError(returncode=sub.returncode,
==> githubactions-runner.amazon-ebs.githubrunner: subprocess.CalledProcessError: Command '/usr/lib/apt/apt-helper cat-file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_jammy_main_cnf_Commands-amd64' returned non-zero exit status 100.
    githubactions-runner.amazon-ebs.githubrunner: Reading package lists...
==> githubactions-runner.amazon-ebs.githubrunner: E: Problem executing scripts APT::Update::Post-Invoke-Success 'if /usr/bin/test -w /var/lib/command-not-found/ -a -e /usr/lib/cnf-update-db; then /usr/lib/cnf-update-db > /dev/null; fi'
==> githubactions-runner.amazon-ebs.githubrunner: E: Sub-process returned an error code
```

I ran: 
```
packer init .
packer validate .
packer build github_agent.ubuntu.pkr.hcl
```
in the ubuntu-jammy directory.

**Comment by fknop** [comment]
Hi, 
I found this in packer docs: 
https://developer.hashicorp.com/packer/docs/debugging#issues-installing-ubuntu-packages
So I added `cloud-init status --wait,`before the `sudo apt-get -y update` and it seems to work for me.

**Comment by bjonnh-work** [comment]
Will try that, thanks!

**Comment by npalm** [comment]
Feel free to raise a PR if the suggestion works.

**Comment by bjonnh-work** [comment]
This works perfectly, I prepare the PR.
Thanks @fknop
