### ISSUE TITLE
Scale-up lambda fails on pool config max capacity

### ISSUE THREAD

**Issue by kflathers-chwy** [philips-labs/terraform-aws-github-runner#3105]
I am using a multi-runner, pool config setup, and I continue to see the following error
```
{
    "errorType": "ScaleError",
    "errorMessage": "No runners create: maximum of runners reached.",
    "name": "ScaleError",
    "stack": [
        "Error: ",
        "    at new ScaleError (/var/task/index.js:137461:22)",
        "    at scaleUp (/var/task/index.js:137898:23)",
        "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
        "    at Runtime.scaleUpHandler [as handler] (/var/task/index.js:137239:9)"
    ]
}
```
I am not seeing any jobs be picked up by the EC2 instances, but I do have hits on the webhook lambda / scale-up lambda.

**Comment by npalm** [comment]
The error should be caused that you have the max number of runners running that you have configured. Which lambda is sending the error? What is your max? Are there instances active. For example the pool will try to create instances no matter if you got events

**Comment by sgametrio** [comment]
I am finding myself in a similar situation. I have the following configuration:
- Pool of runnners of size 1
- Ephemeral runners
- Maximum number of concurrent runners of 15

If I have 25 jobs queued (i.e. 25 webhooks sent), 15 instances will spawn and pick the first 15 jobs, while the other 10 scale-up invocation will end up with `maximum number of runners reached` message. 

Once the job finishes, the instance is teared down (it's ephemeral), but no new instance is created for the remaining 10 queued jobs. I would expect that once the number of runners is lower than the maximum, new runners would be created to fulfill the demand of jobs. I understand that we don't reason in a pull-based setting (checking how many queued jobs are there), but can we retry scaling up for all the times that this was not possible due to `maximum number of runners reached` message? Specifically when using `ephemeral` runners.

@kflathers-chwy do you think it's worth to re-open the issue?
