### ISSUE TITLE
ERR  RunnerServer] System.TimeoutException: The HTTP request timed out after 00:01:00.

### ISSUE THREAD

**Issue by sre-bankly** [philips-labs/terraform-aws-github-runner#3397]
We were using version v4.0.0 when it stopped working. We used a runner on each AWS account in parallel. We identified that the label match started to get confused between the labels created in each account. We destroyed all the runners and uploaded a single one, multi-runner, in version v2.0.0-next.2, which was a version we used before and it worked. However, the same error occurs on everyone we try to climb.

The error below was obtained from the github-self-hosted-runners/multi-runner-linux-arm64/runner log.

```
[2023-07-31 14:00:35Z INFO RunnerServer] EstablishVssConnection
[2023-07-31 14:00:35Z INFO RunnerServer] Establish connection with 60 seconds timeout.
[2023-07-31 14:00:35Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-07-31 14:00:35Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-07-31 14:01:35Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/gWUJRProuscO8vhz7tbQzdi9fTZZxsNdClq3IndVy4liMDjC9P/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-07-31 14:01:35Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-07-31 14:01:35Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-07-31 14:02:15Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/gWUJRProuscO8vhz7tbQzdi9fTZZxsNdClq3IndVy4liMDjC9P/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 100 seconds.
[2023-07-31 14:02:15Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-07-31 14:02:15Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-07-31 14:02:35Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/gWUJRProuscO8vhz7tbQzdi9fTZZxsNdClq3IndVy4liMDjC9P/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-07-31 14:02:35Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-07-31 14:02:35Z INFO RunnerServer] Catch exception during connect. 4 attempt left.
[2023-07-31 14:02:35Z ERR  RunnerServer] System.TimeoutException: The HTTP request timed out after 00:01:00.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at GitHub.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at GitHub.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at GitHub.Runner.Common.RunnerService.EstablishVssConnection(Uri serverUrl, VssCredentials credentials, TimeSpan timeout)
[2023-07-31 14:02:35Z ERR  RunnerServer] #####################################################
[2023-07-31 14:02:35Z ERR  RunnerServer] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at GitHub.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[2023-07-31 14:02:36Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
[2023-07-31 14:02:48Z WARN GitHubActionsService] Attempt 1 of GET request to https://pipelines.actions.githubusercontent.com/gWUJRProuscO8vhz7tbQzdi9fTZZxsNdClq3IndVy4liMDjC9P/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed (Socket Error: NetworkUnreachable). The operation will be retried in 11.058 seconds.
[2023-07-31 14:03:36Z WARN GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/gWUJRProuscO8vhz7tbQzdi9fTZZxsNdClq3IndVy4liMDjC9P/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 timed out after 60 seconds.
[2023-07-31 14:03:36Z INFO GitHubActionsService] Finished operation Location.GetConnectionData
[2023-07-31 14:03:36Z INFO GitHubActionsService] Starting operation Location.GetConnectionData
```

Could you help us? has anyone gone through this?

**Comment by sre-bankly** [comment]
Additional Information:

The instance goes through the webhook matching the labels, the instance goes up, however, the job is waiting for execution. The machine dies, probably because it was idle, and we have to cancel the job otherwise it keeps waiting.
