### ISSUE TITLE
ERR  MessageListener] GitHub.DistributedTask.WebApi.AccessDeniedException: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.

### ISSUE THREAD

**Issue by jhennyssantos** [philips-labs/terraform-aws-github-runner#3419]
We are using runner version 4.1.0, in an AWS account, and we are getting the error below:

```
<html>
<body>
<!--StartFragment-->

[2023-08-09 21:19:22Z ERR  GitHubActionsService] GET request to https://pipelines.actions.githubusercontent.com/wMSElWofsKQEicgR0OLO6wjHbq9wJG6BJg8Odre4O5keY3Dptn/_apis/distributedtask/pools/1/messages?sessionId=99cb3149-c7c3-4fe8-9aac-14c0beed8b8d&status=Online&runnerVersion=2.307.1 failed. HTTP Status: Forbidden, AFD Ref: Ref A: 918490B004B546C79EBB33D707076481 Ref B: BL2AA2030110007 Ref C: 2023-08-09T21:19:22Z
--
[2023-08-09 21:19:22Z ERR  MessageListener] Catch exception during get next message.
[2023-08-09 21:19:22Z ERR  MessageListener] GitHub.DistributedTask.WebApi.AccessDeniedException: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)   at GitHub.Runner.Listener.MessageListener.GetNextMessageAsync(CancellationToken token)
[2023-08-09 21:19:22Z INFO MessageListener] Non-retriable exception: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.
[2023-08-09 21:19:22Z INFO JobDispatcher] Shutting down JobDispatcher. Make sure all WorkerDispatcher has finished.
[2023-08-09 21:19:22Z ERR  GitHubActionsService] DELETE request to https://pipelines.actions.githubusercontent.com/wMSElWofsKQEicgR0OLO6wjHbq9wJG6BJg8Odre4O5keY3Dptn/_apis/distributedtask/pools/1/sessions/99cb3149-c7c3-4fe8-9aac-14c0beed8b8d failed. HTTP Status: Forbidden, AFD Ref: Ref A: 227D635794C3498891DFCED5D37A0BEF Ref B: BL2AA2030110007 Ref C: 2023-08-09T21:19:22Z
[2023-08-09 21:19:22Z INFO Runner] Ignore any exception during DeleteSession for an ephemeral runner. GitHub.DistributedTask.WebApi.AccessDeniedException: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.   at GitHub.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)   at GitHub.Services.WebApi.VssHttpClientBase.SendAsync(HttpMethod method, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)   at GitHub.DistributedTask.WebApi.TaskAgentHttpClientBase.DeleteAgentSessionAsync(Int32 poolId, Guid sessionId, Object userState, CancellationToken cancellationToken)   at GitHub.Runner.Listener.MessageListener.DeleteSessionAsync()   at GitHub.Runner.Listener.Runner.RunAsync(RunnerSettings settings, Boolean runOnce)
[2023-08-09 21:19:22Z ERR  Terminal] WRITE ERROR: An error occurred: Access denied. System:ServiceIdentity;DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD needs View permissions to perform the action.

<!--EndFragment-->
</body>
</html>
```

Can you help us?

We have already granted the role that the runner assumes, the full access permission to AWS resources.

**Comment by jhennyssantos** [comment]
We downgraded to v2.0.0-next.2 and it worked. We had the bug with v4.0.0 and v4.1.0.

Any solution?

**Comment by uklineale** [comment]
This is affecting me as well, but only on the multi-runner module in v4.5.0. The single runner works fine in this version.

**Comment by devshah1** [comment]
@npalm We're facing this error with multi-runner module in latest version ~v5.1.0. I see this bug has been reported in the runner app [here](https://github.com/actions/runner/issues/971). Is that the reason for closing this issue?
