### ISSUE TITLE
PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by relu** [philips-labs/terraform-aws-github-runner#40]
## Summary

Error in scale lambda invocation having to do with the private key decoding.

## Steps to reproduce

The configuration:

```hcl
module "runners" {
  source  = "philips-labs/github-runner/aws"
  version = "~> 0.2"

  ...snip...

  github_app = {
    key_base64     = var.github_app_key_base64
    id             = var.github_app_id
    client_id      = var.github_app_client_id
    client_secret  = var.github_app_client_secret
    webhook_secret = random_password.random.result
  }

  webhook_lambda_zip                = "lambdas-download/webhook.zip"
  runner_binaries_syncer_lambda_zip = "lambdas-download/runner-binaries-syncer.zip"
  runners_lambda_zip                = "lambdas-download/runners.zip"
  enable_organization_runners       = true
  runner_extra_labels               = "default"
}
```

The `github_app_key_base64` which I suspect is the problem is set as following (PKCS#1 RSAPrivateKey):
```
github_app_key_base64    = <<-EOT
-----BEGIN RSA PRIVATE KEY-----
<base64 encoded>
-----END RSA PRIVATE KEY-----
EOT
```

## What is the current *bug* behavior?

`scale` lambda fails.

## What is the expected *correct* behavior?

`scale` lambda succeeds.

## Relevant logs and/or screenshots

```
ERROR	Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:105:29)
    at Object.sign (/var/task/index.js:12802:45)
    at Object.jwsSign [as sign] (/var/task/index.js:9637:24)
    at Object.module.exports.6343.module.exports [as sign] (/var/task/index.js:36570:16)
    at getToken (/var/task/index.js:1861:23)
    at Object.githubAppJwt (/var/task/index.js:1882:23)
    at getAppAuthentication (/var/task/index.js:1509:57)
    at getInstallationAuthentication (/var/task/index.js:1630:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

Kudos for the really nice work on this and for sharing with the community! :)

**Comment by relu** [comment]
Ok, I understand what's going on now, had a quick look over the lambda code and noticed: https://github.com/philips-labs/terraform-aws-github-runner/blob/master/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts#L32

So it looks like it expects the private key to be base64 encoded once more... which is a bit weird if you ask me because the PKCS#1 format is already base64 encoded, hence my confusion.

I'll close this ticket but I do think re-encoding the PKCS#1 pem is unnecessary.
