### ISSUE TITLE
Question: Required Envs for Various Lambda Functions

### ISSUE THREAD

**Issue by callum-tait-pbx** [philips-labs/terraform-aws-github-runner#47]
Hello!

This looks excellent whilst we wait for GitHub to provide a supported solution. I work in a Cloudformation shop however and so I will be converting the Terraform, what isn't super clear to me is what varous env variables I need to provide the various Lambda functions as I will be deploying via Cloudformation and the serverless framework. Could you clarify what is required on the individual lambda functions for them to work?

**Comment by npalm** [comment]
Just simply search the code for:

```hcl

resource "aws_lambda_function" "<lambda_name>" {
  ...
  environment {
    variables = {
      <key> = <value>
    }
  }
}

**Comment by callum-tait-pbx** [comment]
I'm little confused what the ENVIRONMENT variable is used for based on the typescript, could you expand?

**Comment by npalm** [comment]
We use it typically as a kind fo namespace. For example to make names unique. It could also be used to find instances controlled by this deployment to clean up.

**Comment by callum-tait-pbx** [comment]
Hi Again! Thanks for the quick response! I've started deploying the stack however my scale up Lambda errors for reasons I am unsure of. I've removed my secrets from the code below. I can see from the logs the error the is cryptographic related however the stack creates the KMS resource and all my Lambdas are using it so I am not super sure what could go wrong? Googling would suggest it is a cert issue however github posts to my webhook fine and the lambda processes the payload and puts it in the sqs queue.

Terraform code:

```terraform
provider "aws" {
  region  = ""
}

module "github-runner" {
  source  = "philips-labs/github-runner/aws"
  version = "0.2.0"

  aws_region = ""
  vpc_id     = ""
  subnet_ids = ["", ""]

  environment = "gh-ci"

  github_app = {
    key_base64     = "base64string"
    id             = ""
    client_id      = ""
    client_secret  = ""
    webhook_secret = ""
  }

  webhook_lambda_zip                = "built-lambdas/0.2.0/webhook-v0.2.0.zip"
  runner_binaries_syncer_lambda_zip = "built-lambdas/0.2.0/runner-binaries-syncer-v0.2.0.zip"
  runners_lambda_zip                = "built-lambdas/0.2.0/runners-v0.2.0.zip"
  enable_organization_runners = false
}
```

Cloudwatch Logs:
```
2020-07-13T11:52:09.747Z	a54dc058-0dae-5cf2-a7d3-97de40b9fac5	ERROR	Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:105:29)
    at Object.sign (/var/task/index.js:12802:45)
    at Object.jwsSign [as sign] (/var/task/index.js:9637:24)
    at Object.module.exports.6343.module.exports [as sign] (/var/task/index.js:36570:16)
    at getToken (/var/task/index.js:1861:23)
    at Object.githubAppJwt (/var/task/index.js:1882:23)
    at getAppAuthentication (/var/task/index.js:1509:57)
    at getInstallationAuthentication (/var/task/index.js:1630:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}

2020-07-13T11:52:09.765Z	a54dc058-0dae-5cf2-a7d3-97de40b9fac5	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Failed handling SQS event",
    "stack": [
        "Error: Failed handling SQS event",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)",
        "    at postError (/var/runtime/CallbackContext.js:30:54)",
        "    at callback (/var/runtime/CallbackContext.js:42:7)",
        "    at /var/runtime/CallbackContext.js:105:16",
        "    at /var/task/index.js:17333:16",
        "    at Generator.throw (<anonymous>)",
        "    at rejected (/var/task/index.js:17315:65)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```

**Comment by callum-tait-pbx** [comment]
Making progress, not completely deloyed yet but I will raise a new issue if I get more problems, thanks!
