### ISSUE TITLE
Scale up lambda failed with 404 Not Found. POST https://api.github.com/orgs/PavelSusloparov/actions/runners/registration-token

### ISSUE THREAD

**Issue by PavelSusloparov** [philips-labs/terraform-aws-github-runner#722]
Hi. I have an error on the lambda scale up.
Any help appreciated. :)

Cloudwatch logs below:
```
2021-03-30T00:47:40.530Z	9e722d0f-8e64-5322-95ef-75d3f93080d3	ERROR	RequestError [HttpError]: Not Found
    at /var/task/index.js:2791:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 30 Mar 2021 00:47:40 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'A15C:4D88:2437FD:6FD142:6062752C',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4998',
    'x-ratelimit-reset': '1617068858',
    'x-ratelimit-used': '2',
    'x-xss-protection': '0'
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/orgs/PavelSusloparov/actions/runners/registration-token',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.3.5 octokit-core.js/3.2.4 Node.js/12.20.1 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-length': 0
    },
    request: { hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/reference/actions#create-a-registration-token-for-an-organization'
}
```

```
2021-03-30T00:47:40.531Z	9e722d0f-8e64-5322-95ef-75d3f93080d3	ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "Failed handling SQS event",
    "stack": [
        "Error: Failed handling SQS event",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:12:12)",
        "    at postError (/var/runtime/CallbackContext.js:29:54)",
        "    at callback (/var/runtime/CallbackContext.js:41:7)",
        "    at /var/runtime/CallbackContext.js:104:16",
        "    at /var/task/index.js:58015:16",
        "    at Generator.throw (<anonymous>)",
        "    at rejected (/var/task/index.js:57997:65)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
```

**Comment by PavelSusloparov** [comment]
enable_organization_runners was set to true, changed it to false, and was able to run EC2 instance.

404 happened because I run GitHub actions as an individual type of account.
