### ISSUE TITLE
scale-down Error "installationId is set to a falsy value"

### ISSUE THREAD

**Issue by tpatzig** [philips-labs/terraform-aws-github-runner#886]
Hi,

thanks for this great project! We use it with a custom `ghes_url`. 
Everything works fine, except the scale-down.

In the CloudWatch LogGroup we see this Error again and again:

```
2021-06-09T07:25:19.626Z	21246e52-46a0-4387-99b7-e0daebd459ba	ERROR	Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "Error: [@octokit/auth-app] installationId is set to a falsy value",
    "reason": {
        "errorType": "Error",
        "errorMessage": "[@octokit/auth-app] installationId is set to a falsy value",
        "stack": [
            "Error: [@octokit/auth-app] installationId is set to a falsy value",
            "    at Object.createAppAuth (/var/task/index.js:479:11)",
            "    at Object.<anonymous> (/var/task/index.js:60582:42)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/var/task/index.js:60534:58)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: Error: [@octokit/auth-app] installationId is set to a falsy value",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
``` 

Which `installationId` is it refering to, the GH app ID? At least, I can see this is set as env variable on the lambda function.
Any help very much appreciated.

**Comment by evgeniy-kulakov** [comment]
@tpatzig had this issue too after updating to 0.13.1. I suggest using 0.13.0 which works.

**Comment by tpatzig** [comment]
@evgeniy-kulakov thanks! Deployed 0.13.0 and the errors are gone, scale-down works.

**Comment by mrmeyers99** [comment]
I was on 0.13.1.  I tried both upgrading to 0.15.0 and downgrading to 0.13.0 and I'm still getting the `installationId is set to a falsy value` error and scale down isn't working.  Not sure why the downgrade didn't work for me :(

**Comment by npalm** [comment]
Closing the issue due to inactivity, issue seems resolved. Please feel free to re-open
